name: uNAS_env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - pip:
    - -r requirements.txt
  - pytorch
  - pytorch-lightning
  - torchmetrics
  - torchvision
  - torchtext
  - torchaudio
  