name: uNAS-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2022.5.18.1
  - cffi=1.15.0
  - future=0.18.2
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libstdcxx-ng=12.1.0
  - libzlib=1.2.11
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - ncurses=6.3
  - ninja=1.11.0
  - numpy=1.21.6
  - openssl=1.1.1o
  - pip=22.1.2
  - pycparser=2.21
  - python=3.7.13
  - python_abi=3.7
  - pytorch=1.10.2
  - readline=8.1.2
  - setuptools=62.3.4
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==1.1.0
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - braindecode==0.6
    - cachetools==5.2.0
    - certifi==2022.5.18.1
    - charset-normalizer==2.0.12
    - click==8.0.4
    - coverage==5.5
    - cycler==0.11.0
    - cython==0.29.30
    - deprecated==1.2.13
    - dragonfly-opt==0.1.5
    - flatbuffers==2.0
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - gast==0.5.3
    - google-auth==2.7.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==3.7.0
    - idna==3.3
    - importlib-resources==5.7.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.3
    - libclang==14.0.1
    - lxml==4.9.0
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mne==1.0.3
    - moabb==0.4.6
    - msgpack==1.0.4
    - networkx==2.6.3
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.5
    - parameterized==0.8.1
    - pillow==9.1.1
    - pooch==1.6.0
    - pot==0.8.2
    - protobuf==3.19.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.2
    - pyparsing==3.0.9
    - pyriemann==0.2.7
    - pyrsistent==0.18.1
    - pytz==2022.1
    - pyyaml==5.4.1
    - ray==1.13.0
    - redis==4.3.3
    - requests==2.28.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - skorch==0.11.0
    - spektral==1.1.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-addons==0.17.1
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - thop==0.1.0-2207010342
    - threadpoolctl==3.1.0
    - torchsummary==1.5.1
    - tqdm==4.64.0
    - typeguard==2.13.3
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - wrapt==1.14.1
